volumes:
  postgres_data:


networks:
  dev:
    driver: bridge


services:
  db:
    image: postgres:13.0-alpine
    container_name: online_cinema-db
    env_file: Online_cinema/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - dev