# Generated by Django 4.2.23 on 2025-07-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_person_personfilmwork_genrefilmwork_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры'},
        ),
    ]
