# Generated by Django 4.2.23 on 2025-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_filmwork_certificate_filmwork_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.TextField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True, verbose_name='gender'),
        ),
    ]
